/*
 * This file is generated by jOOQ.
 */
package com.example.chatService.entity;



import org.jooq.Catalog;
import org.jooq.EnumType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Status implements EnumType {

    REGISTERED("REGISTERED"),

    VERIFIED("VERIFIED"),

    DELETE("DELETE"),

    BANNED("BANNED");

    private final String literal;

    private Status(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }


    @Override
    public String getName() {
        return "status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static Status lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Status.class, literal);
    }
}
