/*
 * This file is generated by jOOQ.
 */
package com.example.authenticationService.model.jooq.schema.tables.records;


import com.example.authenticationService.model.jooq.schema.enums.Role;
import com.example.authenticationService.model.jooq.schema.enums.Status;
import com.example.authenticationService.model.jooq.schema.enums.Usertype;
import com.example.authenticationService.model.jooq.schema.tables.CianUser;
import com.example.authenticationService.model.jooq.schema.tables.pojos.CianUserEntity;

import java.time.LocalDate;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CianUserRecord extends UpdatableRecordImpl<CianUserRecord> implements Record14<UUID, LocalDate, LocalDate, String, String, String, String, String, String, String, Role, Status, Usertype, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cian_user.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cian_user.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.cian_user.create_date</code>.
     */
    public void setCreateDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cian_user.create_date</code>.
     */
    public LocalDate getCreateDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.cian_user.update_date</code>.
     */
    public void setUpdateDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cian_user.update_date</code>.
     */
    public LocalDate getUpdateDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.cian_user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cian_user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.cian_user.Last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cian_user.Last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.cian_user.patronymic</code>.
     */
    public void setPatronymic(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cian_user.patronymic</code>.
     */
    public String getPatronymic() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.cian_user.logo</code>.
     */
    public void setLogo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.cian_user.logo</code>.
     */
    public String getLogo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.cian_user.phone</code>.
     */
    public void setPhone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.cian_user.phone</code>.
     */
    public String getPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.cian_user.login</code>.
     */
    public void setLogin(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.cian_user.login</code>.
     */
    public String getLogin() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.cian_user.password</code>.
     */
    public void setPassword(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.cian_user.password</code>.
     */
    public String getPassword() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.cian_user.role</code>.
     */
    public void setRole(Role value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.cian_user.role</code>.
     */
    public Role getRole() {
        return (Role) get(10);
    }

    /**
     * Setter for <code>public.cian_user.status</code>.
     */
    public void setStatus(Status value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.cian_user.status</code>.
     */
    public Status getStatus() {
        return (Status) get(11);
    }

    /**
     * Setter for <code>public.cian_user.user_type</code>.
     */
    public void setUserType(Usertype value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.cian_user.user_type</code>.
     */
    public Usertype getUserType() {
        return (Usertype) get(12);
    }

    /**
     * Setter for <code>public.cian_user.redis_id</code>.
     */
    public void setRedisId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.cian_user.redis_id</code>.
     */
    public String getRedisId() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<UUID, LocalDate, LocalDate, String, String, String, String, String, String, String, Role, Status, Usertype, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<UUID, LocalDate, LocalDate, String, String, String, String, String, String, String, Role, Status, Usertype, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return CianUser.CIAN_USER_ENTITY.ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return CianUser.CIAN_USER_ENTITY.CREATE_DATE;
    }

    @Override
    public Field<LocalDate> field3() {
        return CianUser.CIAN_USER_ENTITY.UPDATE_DATE;
    }

    @Override
    public Field<String> field4() {
        return CianUser.CIAN_USER_ENTITY.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return CianUser.CIAN_USER_ENTITY.LAST_NAME;
    }

    @Override
    public Field<String> field6() {
        return CianUser.CIAN_USER_ENTITY.PATRONYMIC;
    }

    @Override
    public Field<String> field7() {
        return CianUser.CIAN_USER_ENTITY.LOGO;
    }

    @Override
    public Field<String> field8() {
        return CianUser.CIAN_USER_ENTITY.PHONE;
    }

    @Override
    public Field<String> field9() {
        return CianUser.CIAN_USER_ENTITY.LOGIN;
    }

    @Override
    public Field<String> field10() {
        return CianUser.CIAN_USER_ENTITY.PASSWORD;
    }

    @Override
    public Field<Role> field11() {
        return CianUser.CIAN_USER_ENTITY.ROLE;
    }

    @Override
    public Field<Status> field12() {
        return CianUser.CIAN_USER_ENTITY.STATUS;
    }

    @Override
    public Field<Usertype> field13() {
        return CianUser.CIAN_USER_ENTITY.USER_TYPE;
    }

    @Override
    public Field<String> field14() {
        return CianUser.CIAN_USER_ENTITY.REDIS_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public LocalDate component2() {
        return getCreateDate();
    }

    @Override
    public LocalDate component3() {
        return getUpdateDate();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public String component6() {
        return getPatronymic();
    }

    @Override
    public String component7() {
        return getLogo();
    }

    @Override
    public String component8() {
        return getPhone();
    }

    @Override
    public String component9() {
        return getLogin();
    }

    @Override
    public String component10() {
        return getPassword();
    }

    @Override
    public Role component11() {
        return getRole();
    }

    @Override
    public Status component12() {
        return getStatus();
    }

    @Override
    public Usertype component13() {
        return getUserType();
    }

    @Override
    public String component14() {
        return getRedisId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public LocalDate value2() {
        return getCreateDate();
    }

    @Override
    public LocalDate value3() {
        return getUpdateDate();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public String value6() {
        return getPatronymic();
    }

    @Override
    public String value7() {
        return getLogo();
    }

    @Override
    public String value8() {
        return getPhone();
    }

    @Override
    public String value9() {
        return getLogin();
    }

    @Override
    public String value10() {
        return getPassword();
    }

    @Override
    public Role value11() {
        return getRole();
    }

    @Override
    public Status value12() {
        return getStatus();
    }

    @Override
    public Usertype value13() {
        return getUserType();
    }

    @Override
    public String value14() {
        return getRedisId();
    }

    @Override
    public CianUserRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public CianUserRecord value2(LocalDate value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public CianUserRecord value3(LocalDate value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public CianUserRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public CianUserRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public CianUserRecord value6(String value) {
        setPatronymic(value);
        return this;
    }

    @Override
    public CianUserRecord value7(String value) {
        setLogo(value);
        return this;
    }

    @Override
    public CianUserRecord value8(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public CianUserRecord value9(String value) {
        setLogin(value);
        return this;
    }

    @Override
    public CianUserRecord value10(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public CianUserRecord value11(Role value) {
        setRole(value);
        return this;
    }

    @Override
    public CianUserRecord value12(Status value) {
        setStatus(value);
        return this;
    }

    @Override
    public CianUserRecord value13(Usertype value) {
        setUserType(value);
        return this;
    }

    @Override
    public CianUserRecord value14(String value) {
        setRedisId(value);
        return this;
    }

    @Override
    public CianUserRecord values(UUID value1, LocalDate value2, LocalDate value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Role value11, Status value12, Usertype value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CianUserRecord
     */
    public CianUserRecord() {
        super(CianUser.CIAN_USER_ENTITY);
    }

    /**
     * Create a detached, initialised CianUserRecord
     */
    public CianUserRecord(UUID id, LocalDate createDate, LocalDate updateDate, String firstName, String lastName, String patronymic, String logo, String phone, String login, String password, Role role, Status status, Usertype userType, String redisId) {
        super(CianUser.CIAN_USER_ENTITY);

        setId(id);
        setCreateDate(createDate);
        setUpdateDate(updateDate);
        setFirstName(firstName);
        setLastName(lastName);
        setPatronymic(patronymic);
        setLogo(logo);
        setPhone(phone);
        setLogin(login);
        setPassword(password);
        setRole(role);
        setStatus(status);
        setUserType(userType);
        setRedisId(redisId);
    }

    /**
     * Create a detached, initialised CianUserRecord
     */
    public CianUserRecord(CianUserEntity value) {
        super(CianUser.CIAN_USER_ENTITY);

        if (value != null) {
            setId(value.getId());
            setCreateDate(value.getCreateDate());
            setUpdateDate(value.getUpdateDate());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setPatronymic(value.getPatronymic());
            setLogo(value.getLogo());
            setPhone(value.getPhone());
            setLogin(value.getLogin());
            setPassword(value.getPassword());
            setRole(value.getRole());
            setStatus(value.getStatus());
            setUserType(value.getUserType());
            setRedisId(value.getRedisId());
        }
    }
}
