/*
 * This file is generated by jOOQ.
 */
package com.example.authenticationService.model.jooq.schema.tables.records;


import com.example.authenticationService.model.jooq.schema.tables.VerificationToken;
import com.example.authenticationService.model.jooq.schema.tables.pojos.VerificationTokenEntity;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerificationTokenRecord extends TableRecordImpl<VerificationTokenRecord> implements Record4<String, UUID, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.verification_token.token</code>.
     */
    public void setToken(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.verification_token.token</code>.
     */
    public String getToken() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.verification_token.userId</code>.
     */
    public void setUserid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.verification_token.userId</code>.
     */
    public UUID getUserid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.verification_token.insert_date</code>.
     */
    public void setInsertDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.verification_token.insert_date</code>.
     */
    public LocalDateTime getInsertDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.verification_token.id</code>.
     */
    public void setId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.verification_token.id</code>.
     */
    public UUID getId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, UUID, LocalDateTime, UUID> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, UUID, LocalDateTime, UUID> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return VerificationToken.VERIFICATION_TOKEN_ENTITY.TOKEN;
    }

    @Override
    public Field<UUID> field2() {
        return VerificationToken.VERIFICATION_TOKEN_ENTITY.USERID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return VerificationToken.VERIFICATION_TOKEN_ENTITY.INSERT_DATE;
    }

    @Override
    public Field<UUID> field4() {
        return VerificationToken.VERIFICATION_TOKEN_ENTITY.ID;
    }

    @Override
    public String component1() {
        return getToken();
    }

    @Override
    public UUID component2() {
        return getUserid();
    }

    @Override
    public LocalDateTime component3() {
        return getInsertDate();
    }

    @Override
    public UUID component4() {
        return getId();
    }

    @Override
    public String value1() {
        return getToken();
    }

    @Override
    public UUID value2() {
        return getUserid();
    }

    @Override
    public LocalDateTime value3() {
        return getInsertDate();
    }

    @Override
    public UUID value4() {
        return getId();
    }

    @Override
    public VerificationTokenRecord value1(String value) {
        setToken(value);
        return this;
    }

    @Override
    public VerificationTokenRecord value2(UUID value) {
        setUserid(value);
        return this;
    }

    @Override
    public VerificationTokenRecord value3(LocalDateTime value) {
        setInsertDate(value);
        return this;
    }

    @Override
    public VerificationTokenRecord value4(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public VerificationTokenRecord values(String value1, UUID value2, LocalDateTime value3, UUID value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VerificationTokenRecord
     */
    public VerificationTokenRecord() {
        super(VerificationToken.VERIFICATION_TOKEN_ENTITY);
    }

    /**
     * Create a detached, initialised VerificationTokenRecord
     */
    public VerificationTokenRecord(String token, UUID userid, LocalDateTime insertDate, UUID id) {
        super(VerificationToken.VERIFICATION_TOKEN_ENTITY);

        setToken(token);
        setUserid(userid);
        setInsertDate(insertDate);
        setId(id);
    }

    /**
     * Create a detached, initialised VerificationTokenRecord
     */
    public VerificationTokenRecord(VerificationTokenEntity value) {
        super(VerificationToken.VERIFICATION_TOKEN_ENTITY);

        if (value != null) {
            setToken(value.getToken());
            setUserid(value.getUserid());
            setInsertDate(value.getInsertDate());
            setId(value.getId());
        }
    }
}
