/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.tables.pojos;


import com.example.advertismentService.entity.Entity;
import com.example.advertismentService.model.jooq.schema.enums.Agentlevel;
import com.example.advertismentService.model.jooq.schema.enums.Status;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgencyEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String name;
    private String description;
    private String phoneNumber;
    private String linkForWebsite;
    private Agentlevel level;
    private Status status;
    private LocalDate insertDate;

    public AgencyEntity() {}

    public AgencyEntity(AgencyEntity value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.phoneNumber = value.phoneNumber;
        this.linkForWebsite = value.linkForWebsite;
        this.level = value.level;
        this.status = value.status;
        this.insertDate = value.insertDate;
    }

    public AgencyEntity(
        UUID id,
        String name,
        String description,
        String phoneNumber,
        String linkForWebsite,
        Agentlevel level,
        Status status,
        LocalDate insertDate
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.phoneNumber = phoneNumber;
        this.linkForWebsite = linkForWebsite;
        this.level = level;
        this.status = status;
        this.insertDate = insertDate;
    }

    /**
     * Getter for <code>public.agency.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.agency.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.agency.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.agency.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.agency.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.agency.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.agency.phone_number</code>.
     */
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Setter for <code>public.agency.phone_number</code>.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for <code>public.agency.link_for_website</code>.
     */
    public String getLinkForWebsite() {
        return this.linkForWebsite;
    }

    /**
     * Setter for <code>public.agency.link_for_website</code>.
     */
    public void setLinkForWebsite(String linkForWebsite) {
        this.linkForWebsite = linkForWebsite;
    }

    /**
     * Getter for <code>public.agency.level</code>.
     */
    public Agentlevel getLevel() {
        return this.level;
    }

    /**
     * Setter for <code>public.agency.level</code>.
     */
    public void setLevel(Agentlevel level) {
        this.level = level;
    }

    /**
     * Getter for <code>public.agency.status</code>.
     */
    public Status getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.agency.status</code>.
     */
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * Getter for <code>public.agency.insert_date</code>.
     */
    public LocalDate getInsertDate() {
        return this.insertDate;
    }

    /**
     * Setter for <code>public.agency.insert_date</code>.
     */
    public void setInsertDate(LocalDate insertDate) {
        this.insertDate = insertDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AgencyEntity other = (AgencyEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.phoneNumber == null) {
            if (other.phoneNumber != null)
                return false;
        }
        else if (!this.phoneNumber.equals(other.phoneNumber))
            return false;
        if (this.linkForWebsite == null) {
            if (other.linkForWebsite != null)
                return false;
        }
        else if (!this.linkForWebsite.equals(other.linkForWebsite))
            return false;
        if (this.level == null) {
            if (other.level != null)
                return false;
        }
        else if (!this.level.equals(other.level))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.insertDate == null) {
            if (other.insertDate != null)
                return false;
        }
        else if (!this.insertDate.equals(other.insertDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.phoneNumber == null) ? 0 : this.phoneNumber.hashCode());
        result = prime * result + ((this.linkForWebsite == null) ? 0 : this.linkForWebsite.hashCode());
        result = prime * result + ((this.level == null) ? 0 : this.level.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.insertDate == null) ? 0 : this.insertDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AgencyEntity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(linkForWebsite);
        sb.append(", ").append(level);
        sb.append(", ").append(status);
        sb.append(", ").append(insertDate);

        sb.append(")");
        return sb.toString();
    }
}
