/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.tables.pojos;


import com.example.advertismentService.entity.Entity;
import com.example.advertismentService.model.jooq.schema.enums.Status;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BuilderEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String name;
    private String description;
    private String linkOnWebsite;
    private String phoneNumber;
    private Status status;
    private LocalDate foundationYear;
    private LocalDate insertDate;

    public BuilderEntity() {}

    public BuilderEntity(BuilderEntity value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.linkOnWebsite = value.linkOnWebsite;
        this.phoneNumber = value.phoneNumber;
        this.status = value.status;
        this.foundationYear = value.foundationYear;
        this.insertDate = value.insertDate;
    }

    public BuilderEntity(
        UUID id,
        String name,
        String description,
        String linkOnWebsite,
        String phoneNumber,
        Status status,
        LocalDate foundationYear,
        LocalDate insertDate
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.linkOnWebsite = linkOnWebsite;
        this.phoneNumber = phoneNumber;
        this.status = status;
        this.foundationYear = foundationYear;
        this.insertDate = insertDate;
    }

    /**
     * Getter for <code>public.builder.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.builder.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.builder.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.builder.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.builder.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.builder.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.builder.link_on_website</code>.
     */
    public String getLinkOnWebsite() {
        return this.linkOnWebsite;
    }

    /**
     * Setter for <code>public.builder.link_on_website</code>.
     */
    public void setLinkOnWebsite(String linkOnWebsite) {
        this.linkOnWebsite = linkOnWebsite;
    }

    /**
     * Getter for <code>public.builder.phone_number</code>.
     */
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Setter for <code>public.builder.phone_number</code>.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for <code>public.builder.status</code>.
     */
    public Status getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.builder.status</code>.
     */
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * Getter for <code>public.builder.foundation_year</code>.
     */
    public LocalDate getFoundationYear() {
        return this.foundationYear;
    }

    /**
     * Setter for <code>public.builder.foundation_year</code>.
     */
    public void setFoundationYear(LocalDate foundationYear) {
        this.foundationYear = foundationYear;
    }

    /**
     * Getter for <code>public.builder.insert_date</code>.
     */
    public LocalDate getInsertDate() {
        return this.insertDate;
    }

    /**
     * Setter for <code>public.builder.insert_date</code>.
     */
    public void setInsertDate(LocalDate insertDate) {
        this.insertDate = insertDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BuilderEntity other = (BuilderEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.linkOnWebsite == null) {
            if (other.linkOnWebsite != null)
                return false;
        }
        else if (!this.linkOnWebsite.equals(other.linkOnWebsite))
            return false;
        if (this.phoneNumber == null) {
            if (other.phoneNumber != null)
                return false;
        }
        else if (!this.phoneNumber.equals(other.phoneNumber))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.foundationYear == null) {
            if (other.foundationYear != null)
                return false;
        }
        else if (!this.foundationYear.equals(other.foundationYear))
            return false;
        if (this.insertDate == null) {
            if (other.insertDate != null)
                return false;
        }
        else if (!this.insertDate.equals(other.insertDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.linkOnWebsite == null) ? 0 : this.linkOnWebsite.hashCode());
        result = prime * result + ((this.phoneNumber == null) ? 0 : this.phoneNumber.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.foundationYear == null) ? 0 : this.foundationYear.hashCode());
        result = prime * result + ((this.insertDate == null) ? 0 : this.insertDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BuilderEntity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(linkOnWebsite);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(status);
        sb.append(", ").append(foundationYear);
        sb.append(", ").append(insertDate);

        sb.append(")");
        return sb.toString();
    }
}
