/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.tables.pojos;


import com.example.advertismentService.entity.Entity;
import com.example.advertismentService.model.jooq.schema.enums.Dealstatus;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DealEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID clientId;
    private UUID brokerId;
    private LocalDate periodOfDeal;
    private Integer transactionAmount;
    private Dealstatus status;
    private LocalDate insertDate;
    private LocalDate transactionDate;
    private UUID realtyId;

    public DealEntity() {}

    public DealEntity(DealEntity value) {
        this.id = value.id;
        this.clientId = value.clientId;
        this.brokerId = value.brokerId;
        this.periodOfDeal = value.periodOfDeal;
        this.transactionAmount = value.transactionAmount;
        this.status = value.status;
        this.insertDate = value.insertDate;
        this.transactionDate = value.transactionDate;
        this.realtyId = value.realtyId;
    }

    public DealEntity(
        UUID id,
        UUID clientId,
        UUID brokerId,
        LocalDate periodOfDeal,
        Integer transactionAmount,
        Dealstatus status,
        LocalDate insertDate,
        LocalDate transactionDate,
        UUID realtyId
    ) {
        this.id = id;
        this.clientId = clientId;
        this.brokerId = brokerId;
        this.periodOfDeal = periodOfDeal;
        this.transactionAmount = transactionAmount;
        this.status = status;
        this.insertDate = insertDate;
        this.transactionDate = transactionDate;
        this.realtyId = realtyId;
    }

    /**
     * Getter for <code>public.deal.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.deal.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.deal.client_id</code>.
     */
    public UUID getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>public.deal.client_id</code>.
     */
    public void setClientId(UUID clientId) {
        this.clientId = clientId;
    }

    /**
     * Getter for <code>public.deal.broker_id</code>.
     */
    public UUID getBrokerId() {
        return this.brokerId;
    }

    /**
     * Setter for <code>public.deal.broker_id</code>.
     */
    public void setBrokerId(UUID brokerId) {
        this.brokerId = brokerId;
    }

    /**
     * Getter for <code>public.deal.period_of_deal</code>.
     */
    public LocalDate getPeriodOfDeal() {
        return this.periodOfDeal;
    }

    /**
     * Setter for <code>public.deal.period_of_deal</code>.
     */
    public void setPeriodOfDeal(LocalDate periodOfDeal) {
        this.periodOfDeal = periodOfDeal;
    }

    /**
     * Getter for <code>public.deal.transaction_amount</code>.
     */
    public Integer getTransactionAmount() {
        return this.transactionAmount;
    }

    /**
     * Setter for <code>public.deal.transaction_amount</code>.
     */
    public void setTransactionAmount(Integer transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    /**
     * Getter for <code>public.deal.status</code>.
     */
    public Dealstatus getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.deal.status</code>.
     */
    public void setStatus(Dealstatus status) {
        this.status = status;
    }

    /**
     * Getter for <code>public.deal.insert_date</code>.
     */
    public LocalDate getInsertDate() {
        return this.insertDate;
    }

    /**
     * Setter for <code>public.deal.insert_date</code>.
     */
    public void setInsertDate(LocalDate insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * Getter for <code>public.deal.transaction_date</code>.
     */
    public LocalDate getTransactionDate() {
        return this.transactionDate;
    }

    /**
     * Setter for <code>public.deal.transaction_date</code>.
     */
    public void setTransactionDate(LocalDate transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * Getter for <code>public.deal.realty_id</code>.
     */
    public UUID getRealtyId() {
        return this.realtyId;
    }

    /**
     * Setter for <code>public.deal.realty_id</code>.
     */
    public void setRealtyId(UUID realtyId) {
        this.realtyId = realtyId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DealEntity other = (DealEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.clientId == null) {
            if (other.clientId != null)
                return false;
        }
        else if (!this.clientId.equals(other.clientId))
            return false;
        if (this.brokerId == null) {
            if (other.brokerId != null)
                return false;
        }
        else if (!this.brokerId.equals(other.brokerId))
            return false;
        if (this.periodOfDeal == null) {
            if (other.periodOfDeal != null)
                return false;
        }
        else if (!this.periodOfDeal.equals(other.periodOfDeal))
            return false;
        if (this.transactionAmount == null) {
            if (other.transactionAmount != null)
                return false;
        }
        else if (!this.transactionAmount.equals(other.transactionAmount))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.insertDate == null) {
            if (other.insertDate != null)
                return false;
        }
        else if (!this.insertDate.equals(other.insertDate))
            return false;
        if (this.transactionDate == null) {
            if (other.transactionDate != null)
                return false;
        }
        else if (!this.transactionDate.equals(other.transactionDate))
            return false;
        if (this.realtyId == null) {
            if (other.realtyId != null)
                return false;
        }
        else if (!this.realtyId.equals(other.realtyId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.clientId == null) ? 0 : this.clientId.hashCode());
        result = prime * result + ((this.brokerId == null) ? 0 : this.brokerId.hashCode());
        result = prime * result + ((this.periodOfDeal == null) ? 0 : this.periodOfDeal.hashCode());
        result = prime * result + ((this.transactionAmount == null) ? 0 : this.transactionAmount.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.insertDate == null) ? 0 : this.insertDate.hashCode());
        result = prime * result + ((this.transactionDate == null) ? 0 : this.transactionDate.hashCode());
        result = prime * result + ((this.realtyId == null) ? 0 : this.realtyId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DealEntity (");

        sb.append(id);
        sb.append(", ").append(clientId);
        sb.append(", ").append(brokerId);
        sb.append(", ").append(periodOfDeal);
        sb.append(", ").append(transactionAmount);
        sb.append(", ").append(status);
        sb.append(", ").append(insertDate);
        sb.append(", ").append(transactionDate);
        sb.append(", ").append(realtyId);

        sb.append(")");
        return sb.toString();
    }
}
