/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.tables.pojos;


import com.example.advertismentService.entity.Entity;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FavouritesEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID clientId;
    private UUID realtyId;

    public FavouritesEntity() {}

    public FavouritesEntity(FavouritesEntity value) {
        this.clientId = value.clientId;
        this.realtyId = value.realtyId;
    }

    public FavouritesEntity(
        UUID clientId,
        UUID realtyId
    ) {
        this.clientId = clientId;
        this.realtyId = realtyId;
    }

    /**
     * Getter for <code>public.favourites.client_id</code>.
     */
    public UUID getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>public.favourites.client_id</code>.
     */
    public void setClientId(UUID clientId) {
        this.clientId = clientId;
    }

    /**
     * Getter for <code>public.favourites.realty_id</code>.
     */
    public UUID getRealtyId() {
        return this.realtyId;
    }

    /**
     * Setter for <code>public.favourites.realty_id</code>.
     */
    public void setRealtyId(UUID realtyId) {
        this.realtyId = realtyId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FavouritesEntity other = (FavouritesEntity) obj;
        if (this.clientId == null) {
            if (other.clientId != null)
                return false;
        }
        else if (!this.clientId.equals(other.clientId))
            return false;
        if (this.realtyId == null) {
            if (other.realtyId != null)
                return false;
        }
        else if (!this.realtyId.equals(other.realtyId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.clientId == null) ? 0 : this.clientId.hashCode());
        result = prime * result + ((this.realtyId == null) ? 0 : this.realtyId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FavouritesEntity (");

        sb.append(clientId);
        sb.append(", ").append(realtyId);

        sb.append(")");
        return sb.toString();
    }
}
