/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.tables.pojos;


import com.example.advertismentService.entity.Entity;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegionsEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer code;
    private String regionName;
    private Integer salesPrice;
    private Integer rentPrice;

    public RegionsEntity() {}

    public RegionsEntity(RegionsEntity value) {
        this.code = value.code;
        this.regionName = value.regionName;
        this.salesPrice = value.salesPrice;
        this.rentPrice = value.rentPrice;
    }

    public RegionsEntity(
        Integer code,
        String regionName,
        Integer salesPrice,
        Integer rentPrice
    ) {
        this.code = code;
        this.regionName = regionName;
        this.salesPrice = salesPrice;
        this.rentPrice = rentPrice;
    }

    /**
     * Getter for <code>public.regions.code</code>.
     */
    public Integer getCode() {
        return this.code;
    }

    /**
     * Setter for <code>public.regions.code</code>.
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * Getter for <code>public.regions.region_name</code>.
     */
    public String getRegionName() {
        return this.regionName;
    }

    /**
     * Setter for <code>public.regions.region_name</code>.
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * Getter for <code>public.regions.sales_price</code>.
     */
    public Integer getSalesPrice() {
        return this.salesPrice;
    }

    /**
     * Setter for <code>public.regions.sales_price</code>.
     */
    public void setSalesPrice(Integer salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * Getter for <code>public.regions.rent_price</code>.
     */
    public Integer getRentPrice() {
        return this.rentPrice;
    }

    /**
     * Setter for <code>public.regions.rent_price</code>.
     */
    public void setRentPrice(Integer rentPrice) {
        this.rentPrice = rentPrice;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RegionsEntity other = (RegionsEntity) obj;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.regionName == null) {
            if (other.regionName != null)
                return false;
        }
        else if (!this.regionName.equals(other.regionName))
            return false;
        if (this.salesPrice == null) {
            if (other.salesPrice != null)
                return false;
        }
        else if (!this.salesPrice.equals(other.salesPrice))
            return false;
        if (this.rentPrice == null) {
            if (other.rentPrice != null)
                return false;
        }
        else if (!this.rentPrice.equals(other.rentPrice))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.regionName == null) ? 0 : this.regionName.hashCode());
        result = prime * result + ((this.salesPrice == null) ? 0 : this.salesPrice.hashCode());
        result = prime * result + ((this.rentPrice == null) ? 0 : this.rentPrice.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RegionsEntity (");

        sb.append(code);
        sb.append(", ").append(regionName);
        sb.append(", ").append(salesPrice);
        sb.append(", ").append(rentPrice);

        sb.append(")");
        return sb.toString();
    }
}
