/*
 * This file is generated by jOOQ.
 */
package com.example.authenticationService.model.jooq.schema;


import com.example.authenticationService.model.jooq.schema.tables.Agent;
import com.example.authenticationService.model.jooq.schema.tables.CianUser;
import com.example.authenticationService.model.jooq.schema.tables.Organisation;
import com.example.authenticationService.model.jooq.schema.tables.RefreshToken;
import com.example.authenticationService.model.jooq.schema.tables.VerificationToken;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.agent</code>.
     */
    public final Agent AGENT_ENTITY = Agent.AGENT_ENTITY;

    /**
     * The table <code>public.cian_user</code>.
     */
    public final CianUser CIAN_USER_ENTITY = CianUser.CIAN_USER_ENTITY;

    /**
     * The table <code>public.organisation</code>.
     */
    public final Organisation ORGANISATION_ENTITY = Organisation.ORGANISATION_ENTITY;

    /**
     * The table <code>public.refresh_token</code>.
     */
    public final RefreshToken REFRESH_TOKEN_ENTITY = RefreshToken.REFRESH_TOKEN_ENTITY;

    /**
     * The table <code>public.verification_token</code>.
     */
    public final VerificationToken VERIFICATION_TOKEN_ENTITY = VerificationToken.VERIFICATION_TOKEN_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Agent.AGENT_ENTITY,
            CianUser.CIAN_USER_ENTITY,
            Organisation.ORGANISATION_ENTITY,
            RefreshToken.REFRESH_TOKEN_ENTITY,
            VerificationToken.VERIFICATION_TOKEN_ENTITY
        );
    }
}
