/*
 * This file is generated by jOOQ.
 */
package com.example.authenticationService.model.jooq.schema;


import com.example.authenticationService.model.jooq.schema.tables.Agent;
import com.example.authenticationService.model.jooq.schema.tables.CianUser;
import com.example.authenticationService.model.jooq.schema.tables.Organisation;
import com.example.authenticationService.model.jooq.schema.tables.RefreshToken;
import com.example.authenticationService.model.jooq.schema.tables.VerificationToken;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.agent</code>.
     */
    public static final Agent AGENT_ENTITY = Agent.AGENT_ENTITY;

    /**
     * The table <code>public.cian_user</code>.
     */
    public static final CianUser CIAN_USER_ENTITY = CianUser.CIAN_USER_ENTITY;

    /**
     * The table <code>public.organisation</code>.
     */
    public static final Organisation ORGANISATION_ENTITY = Organisation.ORGANISATION_ENTITY;

    /**
     * The table <code>public.refresh_token</code>.
     */
    public static final RefreshToken REFRESH_TOKEN_ENTITY = RefreshToken.REFRESH_TOKEN_ENTITY;

    /**
     * The table <code>public.verification_token</code>.
     */
    public static final VerificationToken VERIFICATION_TOKEN_ENTITY = VerificationToken.VERIFICATION_TOKEN_ENTITY;
}
