/*
 * This file is generated by jOOQ.
 */
package com.example.fileservice.model.jooq.schema;


import com.example.fileservice.model.jooq.schema.tables.File;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.file</code>.
     */
    public static final File FILE_ENTITY = File.FILE_ENTITY;
}
