/*
 * This file is generated by jOOQ.
 */
package com.example.chatService.model.jooq.schema;


import com.example.chatService.model.jooq.schema.tables.ChatRoom;
import com.example.chatService.model.jooq.schema.tables.Message;
import com.example.chatService.model.jooq.schema.tables.Notification;
import com.example.chatService.model.jooq.schema.tables.records.ChatRoomRecord;
import com.example.chatService.model.jooq.schema.tables.records.MessageRecord;
import com.example.chatService.model.jooq.schema.tables.records.NotificationRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRoomRecord> PK_CHAT = Internal.createUniqueKey(ChatRoom.CHAT_ROOM_ENTITY, DSL.name("pk_chat"), new TableField[] { ChatRoom.CHAT_ROOM_ENTITY.ID }, true);
    public static final UniqueKey<MessageRecord> MESSAGE_PKEY = Internal.createUniqueKey(Message.MESSAGE_ENTITY, DSL.name("message_pkey"), new TableField[] { Message.MESSAGE_ENTITY.ID }, true);
    public static final UniqueKey<NotificationRecord> PK_MESSAGE = Internal.createUniqueKey(Notification.NOTIFICATION_ENTITY, DSL.name("pk_message"), new TableField[] { Notification.NOTIFICATION_ENTITY.ID }, true);
}
