/*
 * This file is generated by jOOQ.
 */
package com.example.chatService.model.jooq.schema;


import com.example.chatService.model.jooq.schema.tables.ChatAndUser;
import com.example.chatService.model.jooq.schema.tables.ChatRoom;
import com.example.chatService.model.jooq.schema.tables.Message;
import com.example.chatService.model.jooq.schema.tables.Notification;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.chat_and_user</code>.
     */
    public static final ChatAndUser CHAT_AND_USER_ENTITY = ChatAndUser.CHAT_AND_USER_ENTITY;

    /**
     * The table <code>public.chat_room</code>.
     */
    public static final ChatRoom CHAT_ROOM_ENTITY = ChatRoom.CHAT_ROOM_ENTITY;

    /**
     * The table <code>public.message</code>.
     */
    public static final Message MESSAGE_ENTITY = Message.MESSAGE_ENTITY;

    /**
     * The table <code>public.notification</code>.
     */
    public static final Notification NOTIFICATION_ENTITY = Notification.NOTIFICATION_ENTITY;
}
