/*
 * This file is generated by jOOQ.
 */
package com.example.authenticationService.entity;



import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID chatId;
    private UUID senderId;
    private UUID recipientId;
    private String senderName;
    private String recipientName;
    private String content;

    public MessageEntity() {}

    public MessageEntity(MessageEntity value) {
        this.chatId = value.chatId;
        this.senderId = value.senderId;
        this.recipientId = value.recipientId;
        this.senderName = value.senderName;
        this.recipientName = value.recipientName;
        this.content = value.content;
    }

    public MessageEntity(
        UUID chatId,
        UUID senderId,
        UUID recipientId,
        String senderName,
        String recipientName,
        String content
    ) {
        this.chatId = chatId;
        this.senderId = senderId;
        this.recipientId = recipientId;
        this.senderName = senderName;
        this.recipientName = recipientName;
        this.content = content;
    }



    /**
     * Getter for <code>public.message.chat_id</code>.
     */
    public UUID getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.message.chat_id</code>.
     */
    public void setChatId(UUID chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.message.sender_id</code>.
     */
    public UUID getSenderId() {
        return this.senderId;
    }

    /**
     * Setter for <code>public.message.sender_id</code>.
     */
    public void setSenderId(UUID senderId) {
        this.senderId = senderId;
    }

    /**
     * Getter for <code>public.message.recipient_id</code>.
     */
    public UUID getRecipientId() {
        return this.recipientId;
    }

    /**
     * Setter for <code>public.message.recipient_id</code>.
     */
    public void setRecipientId(UUID recipientId) {
        this.recipientId = recipientId;
    }

    /**
     * Getter for <code>public.message.sender_name</code>.
     */
    public String getSenderName() {
        return this.senderName;
    }

    /**
     * Setter for <code>public.message.sender_name</code>.
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    /**
     * Getter for <code>public.message.recipient_name</code>.
     */
    public String getRecipientName() {
        return this.recipientName;
    }

    /**
     * Setter for <code>public.message.recipient_name</code>.
     */
    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName;
    }

    /**
     * Getter for <code>public.message.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>public.message.content</code>.
     */
    public void setContent(String content) {
        this.content = content;
    }



    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MessageEntity other = (MessageEntity) obj;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.senderId == null) {
            if (other.senderId != null)
                return false;
        }
        else if (!this.senderId.equals(other.senderId))
            return false;
        if (this.recipientId == null) {
            if (other.recipientId != null)
                return false;
        }
        else if (!this.recipientId.equals(other.recipientId))
            return false;
        if (this.senderName == null) {
            if (other.senderName != null)
                return false;
        }
        else if (!this.senderName.equals(other.senderName))
            return false;
        if (this.recipientName == null) {
            if (other.recipientName != null)
                return false;
        }
        else if (!this.recipientName.equals(other.recipientName))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.senderId == null) ? 0 : this.senderId.hashCode());
        result = prime * result + ((this.recipientId == null) ? 0 : this.recipientId.hashCode());
        result = prime * result + ((this.senderName == null) ? 0 : this.senderName.hashCode());
        result = prime * result + ((this.recipientName == null) ? 0 : this.recipientName.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MessageEntity (");

        sb.append(", ").append(chatId);
        sb.append(", ").append(senderId);
        sb.append(", ").append(recipientId);
        sb.append(", ").append(senderName);
        sb.append(", ").append(recipientName);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
