/*
 * This file is generated by jOOQ.
 */
package com.example.chatService.model.jooq.schema.tables.pojos;


import com.example.chatService.entity.Entity;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatAndUserEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID userId;
    private String chatId;
    private Boolean isadmin;

    public ChatAndUserEntity() {}

    public ChatAndUserEntity(ChatAndUserEntity value) {
        this.userId = value.userId;
        this.chatId = value.chatId;
        this.isadmin = value.isadmin;
    }

    public ChatAndUserEntity(
        UUID userId,
        String chatId,
        Boolean isadmin
    ) {
        this.userId = userId;
        this.chatId = chatId;
        this.isadmin = isadmin;
    }

    /**
     * Getter for <code>public.chat_and_user.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.chat_and_user.user_id</code>.
     */
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.chat_and_user.chat_id</code>.
     */
    public String getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.chat_and_user.chat_id</code>.
     */
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.chat_and_user.isAdmin</code>.
     */
    public Boolean getIsadmin() {
        return this.isadmin;
    }

    /**
     * Setter for <code>public.chat_and_user.isAdmin</code>.
     */
    public void setIsadmin(Boolean isadmin) {
        this.isadmin = isadmin;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChatAndUserEntity other = (ChatAndUserEntity) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.isadmin == null) {
            if (other.isadmin != null)
                return false;
        }
        else if (!this.isadmin.equals(other.isadmin))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.isadmin == null) ? 0 : this.isadmin.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatAndUserEntity (");

        sb.append(userId);
        sb.append(", ").append(chatId);
        sb.append(", ").append(isadmin);

        sb.append(")");
        return sb.toString();
    }
}
