/*
 * This file is generated by jOOQ.
 */
package com.example.fileservice.model.jooq.schema.enums;


import com.example.fileservice.model.jooq.schema.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EntityType implements EnumType {

    BUILDER("BUILDER"),

    AGENCY("AGENCY"),

    AGENT("AGENT"),

    OWNER("OWNER"),

    USER("USER"),

    RESIDENTIAL_COMPLEX("RESIDENTIAL_COMPLEX"),

    FLAT("FLAT"),

    HOUSE("HOUSE");

    private final String literal;

    private EntityType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "entity_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static EntityType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(EntityType.class, literal);
    }
}
