/*
 * This file is generated by jOOQ.
 */
package com.example.fileservice.model.jooq.schema.enums;


import com.example.fileservice.model.jooq.schema.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum FileType implements EnumType {

    REGULATION("REGULATION"),

    OGRN("OGRN"),

    EGRUL("EGRUL"),

    ORGNIP("ORGNIP"),

    EGRIP("EGRIP"),

    INN("INN"),

    EGRN("EGRN"),

    PERSON("PERSON"),

    LOGO("LOGO"),

    HEAT("HEAT"),

    VIEW("VIEW");

    private final String literal;

    private FileType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "file_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static FileType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(FileType.class, literal);
    }
}
