/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema;


import com.example.advertismentService.model.jooq.schema.tables.Agency;
import com.example.advertismentService.model.jooq.schema.tables.Builder;
import com.example.advertismentService.model.jooq.schema.tables.Deal;
import com.example.advertismentService.model.jooq.schema.tables.Favourites;
import com.example.advertismentService.model.jooq.schema.tables.Flat;
import com.example.advertismentService.model.jooq.schema.tables.House;
import com.example.advertismentService.model.jooq.schema.tables.Realty;
import com.example.advertismentService.model.jooq.schema.tables.Regions;
import com.example.advertismentService.model.jooq.schema.tables.RegionsAndAgency;
import com.example.advertismentService.model.jooq.schema.tables.ResidentialComplex;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.agency</code>.
     */
    public static final Agency AGENCY_ENTITY = Agency.AGENCY_ENTITY;

    /**
     * The table <code>public.builder</code>.
     */
    public static final Builder BUILDER_ENTITY = Builder.BUILDER_ENTITY;

    /**
     * The table <code>public.deal</code>.
     */
    public static final Deal DEAL_ENTITY = Deal.DEAL_ENTITY;

    /**
     * The table <code>public.favourites</code>.
     */
    public static final Favourites FAVOURITES_ENTITY = Favourites.FAVOURITES_ENTITY;

    /**
     * The table <code>public.flat</code>.
     */
    public static final Flat FLAT_ENTITY = Flat.FLAT_ENTITY;

    /**
     * The table <code>public.house</code>.
     */
    public static final House HOUSE_ENTITY = House.HOUSE_ENTITY;

    /**
     * The table <code>public.realty</code>.
     */
    public static final Realty REALTY_ENTITY = Realty.REALTY_ENTITY;

    /**
     * The table <code>public.regions</code>.
     */
    public static final Regions REGIONS_ENTITY = Regions.REGIONS_ENTITY;

    /**
     * The table <code>public.regions_and_agency</code>.
     */
    public static final RegionsAndAgency REGIONS_AND_AGENCY_ENTITY = RegionsAndAgency.REGIONS_AND_AGENCY_ENTITY;

    /**
     * The table <code>public.residential_complex</code>.
     */
    public static final ResidentialComplex RESIDENTIAL_COMPLEX_ENTITY = ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY;
}
