/*
 * This file is generated by jOOQ.
 */
package com.example.authenticationService.model.jooq.schema.tables.pojos;


import com.example.authenticationService.model.jooq.schema.enums.Agentlevel;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgentEntity extends CianUserEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Agentlevel experience;
    private UUID id;
    private UUID agencyId;

    public AgentEntity() {}

    public AgentEntity(AgentEntity value) {
        this.experience = value.experience;
        this.id = value.id;
        this.agencyId = value.agencyId;
    }

    public AgentEntity(
        Agentlevel experience,
        UUID id,
        UUID agencyId
    ) {
        this.experience = experience;
        this.id = id;
        this.agencyId = agencyId;
    }

    /**
     * Getter for <code>public.agent.experience</code>.
     */
    public Agentlevel getExperience() {
        return this.experience;
    }

    /**
     * Setter for <code>public.agent.experience</code>.
     */
    public void setExperience(Agentlevel experience) {
        this.experience = experience;
    }

    /**
     * Getter for <code>public.agent.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.agent.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.agent.agency_id</code>.
     */
    public UUID getAgencyId() {
        return this.agencyId;
    }

    /**
     * Setter for <code>public.agent.agency_id</code>.
     */
    public void setAgencyId(UUID agencyId) {
        this.agencyId = agencyId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AgentEntity other = (AgentEntity) obj;
        if (this.experience == null) {
            if (other.experience != null)
                return false;
        }
        else if (!this.experience.equals(other.experience))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.agencyId == null) {
            if (other.agencyId != null)
                return false;
        }
        else if (!this.agencyId.equals(other.agencyId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.experience == null) ? 0 : this.experience.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.agencyId == null) ? 0 : this.agencyId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AgentEntity (");

        sb.append(experience);
        sb.append(", ").append(id);
        sb.append(", ").append(agencyId);

        sb.append(")");
        return sb.toString();
    }
}
