/*
 * This file is generated by jOOQ.
 */
package com.example.authenticationService.model.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationEntity extends CianUserEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID organisationId;

    public OrganisationEntity() {}

    public OrganisationEntity(OrganisationEntity value) {
        this.id = value.id;
        this.organisationId = value.organisationId;
    }

    public OrganisationEntity(
        UUID id,
        UUID organisationId
    ) {
        this.id = id;
        this.organisationId = organisationId;
    }

    /**
     * Getter for <code>public.organisation.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.organisation.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.organisation.organisation_id</code>.
     */
    public UUID getOrganisationId() {
        return this.organisationId;
    }

    /**
     * Setter for <code>public.organisation.organisation_id</code>.
     */
    public void setOrganisationId(UUID organisationId) {
        this.organisationId = organisationId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrganisationEntity other = (OrganisationEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.organisationId == null) {
            if (other.organisationId != null)
                return false;
        }
        else if (!this.organisationId.equals(other.organisationId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.organisationId == null) ? 0 : this.organisationId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrganisationEntity (");

        sb.append(id);
        sb.append(", ").append(organisationId);

        sb.append(")");
        return sb.toString();
    }
}
