/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.enums;


import com.example.advertismentService.model.jooq.schema.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Adverttype implements EnumType {

    PERMANENT("PERMANENT"),

    MONTH("MONTH"),

    DAY("DAY"),

    YEAR("YEAR");

    private final String literal;

    private Adverttype(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "adverttype";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static Adverttype lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Adverttype.class, literal);
    }
}
