/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.enums;


import com.example.advertismentService.model.jooq.schema.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Dealstatus implements EnumType {

    COMPLETED("COMPLETED"),

    THWARTED("THWARTED"),

    IN_PROCESS("IN_PROCESS");

    private final String literal;

    private Dealstatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "dealstatus";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static Dealstatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Dealstatus.class, literal);
    }
}
