/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.enums;


import com.example.advertismentService.model.jooq.schema.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Material implements EnumType {

    BALK("BALK"),

    BRICK("BRICK"),

    AEROCRETE("AEROCRETE");

    private final String literal;

    private Material(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "material";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static Material lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Material.class, literal);
    }
}
