/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.enums;


import com.example.advertismentService.model.jooq.schema.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Tariff implements EnumType {

    WITH_NO_DOCUMENTS("WITH_NO_DOCUMENTS"),

    STANDART("STANDART"),

    PREMIUM("PREMIUM"),

    TOP("TOP"),

    BUILDER("BUILDER");

    private final String literal;

    private Tariff(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "tariff";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static Tariff lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Tariff.class, literal);
    }
}
