/*
 * This file is generated by jOOQ.
 */
package com.example.chatService.model.jooq.schema.tables.records;


import com.example.chatService.model.jooq.schema.enums.Cause;
import com.example.chatService.model.jooq.schema.tables.Notification;
import com.example.chatService.model.jooq.schema.tables.pojos.NotificationEntity;

import java.time.LocalDate;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationRecord extends UpdatableRecordImpl<NotificationRecord> implements Record5<UUID, Cause, String, LocalDate, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.notification.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notification.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.notification.cause_of_message</code>.
     */
    public void setCauseOfMessage(Cause value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notification.cause_of_message</code>.
     */
    public Cause getCauseOfMessage() {
        return (Cause) get(1);
    }

    /**
     * Setter for <code>public.notification.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notification.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.notification.create_date</code>.
     */
    public void setCreateDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notification.create_date</code>.
     */
    public LocalDate getCreateDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.notification.recipient_id</code>.
     */
    public void setRecipientId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notification.recipient_id</code>.
     */
    public String getRecipientId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, Cause, String, LocalDate, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, Cause, String, LocalDate, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Notification.NOTIFICATION_ENTITY.ID;
    }

    @Override
    public Field<Cause> field2() {
        return Notification.NOTIFICATION_ENTITY.CAUSE_OF_MESSAGE;
    }

    @Override
    public Field<String> field3() {
        return Notification.NOTIFICATION_ENTITY.CONTENT;
    }

    @Override
    public Field<LocalDate> field4() {
        return Notification.NOTIFICATION_ENTITY.CREATE_DATE;
    }

    @Override
    public Field<String> field5() {
        return Notification.NOTIFICATION_ENTITY.RECIPIENT_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public Cause component2() {
        return getCauseOfMessage();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public LocalDate component4() {
        return getCreateDate();
    }

    @Override
    public String component5() {
        return getRecipientId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public Cause value2() {
        return getCauseOfMessage();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public LocalDate value4() {
        return getCreateDate();
    }

    @Override
    public String value5() {
        return getRecipientId();
    }

    @Override
    public NotificationRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationRecord value2(Cause value) {
        setCauseOfMessage(value);
        return this;
    }

    @Override
    public NotificationRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public NotificationRecord value4(LocalDate value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public NotificationRecord value5(String value) {
        setRecipientId(value);
        return this;
    }

    @Override
    public NotificationRecord values(UUID value1, Cause value2, String value3, LocalDate value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationRecord
     */
    public NotificationRecord() {
        super(Notification.NOTIFICATION_ENTITY);
    }

    /**
     * Create a detached, initialised NotificationRecord
     */
    public NotificationRecord(UUID id, Cause causeOfMessage, String content, LocalDate createDate, String recipientId) {
        super(Notification.NOTIFICATION_ENTITY);

        setId(id);
        setCauseOfMessage(causeOfMessage);
        setContent(content);
        setCreateDate(createDate);
        setRecipientId(recipientId);
    }

    /**
     * Create a detached, initialised NotificationRecord
     */
    public NotificationRecord(NotificationEntity value) {
        super(Notification.NOTIFICATION_ENTITY);

        if (value != null) {
            setId(value.getId());
            setCauseOfMessage(value.getCauseOfMessage());
            setContent(value.getContent());
            setCreateDate(value.getCreateDate());
            setRecipientId(value.getRecipientId());
        }
    }
}
