/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.tables.records;


import com.example.advertismentService.model.jooq.schema.enums.Status;
import com.example.advertismentService.model.jooq.schema.tables.Builder;
import com.example.advertismentService.model.jooq.schema.tables.pojos.BuilderEntity;

import java.time.LocalDate;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BuilderRecord extends UpdatableRecordImpl<BuilderRecord> implements Record8<UUID, String, String, String, String, Status, LocalDate, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.builder.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.builder.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.builder.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.builder.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.builder.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.builder.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.builder.link_on_website</code>.
     */
    public void setLinkOnWebsite(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.builder.link_on_website</code>.
     */
    public String getLinkOnWebsite() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.builder.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.builder.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.builder.status</code>.
     */
    public void setStatus(Status value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.builder.status</code>.
     */
    public Status getStatus() {
        return (Status) get(5);
    }

    /**
     * Setter for <code>public.builder.foundation_year</code>.
     */
    public void setFoundationYear(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.builder.foundation_year</code>.
     */
    public LocalDate getFoundationYear() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>public.builder.insert_date</code>.
     */
    public void setInsertDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.builder.insert_date</code>.
     */
    public LocalDate getInsertDate() {
        return (LocalDate) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, String, String, String, Status, LocalDate, LocalDate> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, String, String, String, String, Status, LocalDate, LocalDate> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Builder.BUILDER_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return Builder.BUILDER_ENTITY.NAME;
    }

    @Override
    public Field<String> field3() {
        return Builder.BUILDER_ENTITY.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Builder.BUILDER_ENTITY.LINK_ON_WEBSITE;
    }

    @Override
    public Field<String> field5() {
        return Builder.BUILDER_ENTITY.PHONE_NUMBER;
    }

    @Override
    public Field<Status> field6() {
        return Builder.BUILDER_ENTITY.STATUS;
    }

    @Override
    public Field<LocalDate> field7() {
        return Builder.BUILDER_ENTITY.FOUNDATION_YEAR;
    }

    @Override
    public Field<LocalDate> field8() {
        return Builder.BUILDER_ENTITY.INSERT_DATE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getLinkOnWebsite();
    }

    @Override
    public String component5() {
        return getPhoneNumber();
    }

    @Override
    public Status component6() {
        return getStatus();
    }

    @Override
    public LocalDate component7() {
        return getFoundationYear();
    }

    @Override
    public LocalDate component8() {
        return getInsertDate();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getLinkOnWebsite();
    }

    @Override
    public String value5() {
        return getPhoneNumber();
    }

    @Override
    public Status value6() {
        return getStatus();
    }

    @Override
    public LocalDate value7() {
        return getFoundationYear();
    }

    @Override
    public LocalDate value8() {
        return getInsertDate();
    }

    @Override
    public BuilderRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public BuilderRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public BuilderRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public BuilderRecord value4(String value) {
        setLinkOnWebsite(value);
        return this;
    }

    @Override
    public BuilderRecord value5(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public BuilderRecord value6(Status value) {
        setStatus(value);
        return this;
    }

    @Override
    public BuilderRecord value7(LocalDate value) {
        setFoundationYear(value);
        return this;
    }

    @Override
    public BuilderRecord value8(LocalDate value) {
        setInsertDate(value);
        return this;
    }

    @Override
    public BuilderRecord values(UUID value1, String value2, String value3, String value4, String value5, Status value6, LocalDate value7, LocalDate value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BuilderRecord
     */
    public BuilderRecord() {
        super(Builder.BUILDER_ENTITY);
    }

    /**
     * Create a detached, initialised BuilderRecord
     */
    public BuilderRecord(UUID id, String name, String description, String linkOnWebsite, String phoneNumber, Status status, LocalDate foundationYear, LocalDate insertDate) {
        super(Builder.BUILDER_ENTITY);

        setId(id);
        setName(name);
        setDescription(description);
        setLinkOnWebsite(linkOnWebsite);
        setPhoneNumber(phoneNumber);
        setStatus(status);
        setFoundationYear(foundationYear);
        setInsertDate(insertDate);
    }

    /**
     * Create a detached, initialised BuilderRecord
     */
    public BuilderRecord(BuilderEntity value) {
        super(Builder.BUILDER_ENTITY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setLinkOnWebsite(value.getLinkOnWebsite());
            setPhoneNumber(value.getPhoneNumber());
            setStatus(value.getStatus());
            setFoundationYear(value.getFoundationYear());
            setInsertDate(value.getInsertDate());
        }
    }
}
