/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.tables.records;


import com.example.advertismentService.model.jooq.schema.enums.Adverttype;
import com.example.advertismentService.model.jooq.schema.enums.FlatOrHouse;
import com.example.advertismentService.model.jooq.schema.enums.Ownertype;
import com.example.advertismentService.model.jooq.schema.enums.Realtystatus;
import com.example.advertismentService.model.jooq.schema.enums.Tariff;
import com.example.advertismentService.model.jooq.schema.tables.Realty;
import com.example.advertismentService.model.jooq.schema.tables.pojos.RealtyEntity;

import java.time.LocalDate;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RealtyRecord extends UpdatableRecordImpl<RealtyRecord> implements Record18<UUID, UUID, Double, String, String, String, String, Adverttype, Integer, Tariff, FlatOrHouse, LocalDate, LocalDate, LocalDate, Realtystatus, UUID, Ownertype, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.realty.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.realty.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.realty.owner_id</code>.
     */
    public void setOwnerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.realty.owner_id</code>.
     */
    public UUID getOwnerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.realty.square</code>.
     */
    public void setSquare(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.realty.square</code>.
     */
    public Double getSquare() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.realty.region</code>.
     */
    public void setRegion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.realty.region</code>.
     */
    public String getRegion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.realty.district</code>.
     */
    public void setDistrict(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.realty.district</code>.
     */
    public String getDistrict() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.realty.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.realty.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.realty.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.realty.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.realty.advert_type</code>.
     */
    public void setAdvertType(Adverttype value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.realty.advert_type</code>.
     */
    public Adverttype getAdvertType() {
        return (Adverttype) get(7);
    }

    /**
     * Setter for <code>public.realty.cost</code>.
     */
    public void setCost(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.realty.cost</code>.
     */
    public Integer getCost() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.realty.tariff_type</code>.
     */
    public void setTariffType(Tariff value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.realty.tariff_type</code>.
     */
    public Tariff getTariffType() {
        return (Tariff) get(9);
    }

    /**
     * Setter for <code>public.realty.flat_or_house</code>.
     */
    public void setFlatOrHouse(FlatOrHouse value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.realty.flat_or_house</code>.
     */
    public FlatOrHouse getFlatOrHouse() {
        return (FlatOrHouse) get(10);
    }

    /**
     * Setter for <code>public.realty.insert_date</code>.
     */
    public void setInsertDate(LocalDate value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.realty.insert_date</code>.
     */
    public LocalDate getInsertDate() {
        return (LocalDate) get(11);
    }

    /**
     * Setter for <code>public.realty.update_date</code>.
     */
    public void setUpdateDate(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.realty.update_date</code>.
     */
    public LocalDate getUpdateDate() {
        return (LocalDate) get(12);
    }

    /**
     * Setter for <code>public.realty.release_date</code>.
     */
    public void setReleaseDate(LocalDate value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.realty.release_date</code>.
     */
    public LocalDate getReleaseDate() {
        return (LocalDate) get(13);
    }

    /**
     * Setter for <code>public.realty.status</code>.
     */
    public void setStatus(Realtystatus value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.realty.status</code>.
     */
    public Realtystatus getStatus() {
        return (Realtystatus) get(14);
    }

    /**
     * Setter for <code>public.realty.complex_id</code>.
     */
    public void setComplexId(UUID value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.realty.complex_id</code>.
     */
    public UUID getComplexId() {
        return (UUID) get(15);
    }

    /**
     * Setter for <code>public.realty.owner_type</code>.
     */
    public void setOwnerType(Ownertype value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.realty.owner_type</code>.
     */
    public Ownertype getOwnerType() {
        return (Ownertype) get(16);
    }

    /**
     * Setter for <code>public.realty.verify</code>.
     */
    public void setVerify(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.realty.verify</code>.
     */
    public Boolean getVerify() {
        return (Boolean) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<UUID, UUID, Double, String, String, String, String, Adverttype, Integer, Tariff, FlatOrHouse, LocalDate, LocalDate, LocalDate, Realtystatus, UUID, Ownertype, Boolean> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<UUID, UUID, Double, String, String, String, String, Adverttype, Integer, Tariff, FlatOrHouse, LocalDate, LocalDate, LocalDate, Realtystatus, UUID, Ownertype, Boolean> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Realty.REALTY_ENTITY.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Realty.REALTY_ENTITY.OWNER_ID;
    }

    @Override
    public Field<Double> field3() {
        return Realty.REALTY_ENTITY.SQUARE;
    }

    @Override
    public Field<String> field4() {
        return Realty.REALTY_ENTITY.REGION;
    }

    @Override
    public Field<String> field5() {
        return Realty.REALTY_ENTITY.DISTRICT;
    }

    @Override
    public Field<String> field6() {
        return Realty.REALTY_ENTITY.ADDRESS;
    }

    @Override
    public Field<String> field7() {
        return Realty.REALTY_ENTITY.DESCRIPTION;
    }

    @Override
    public Field<Adverttype> field8() {
        return Realty.REALTY_ENTITY.ADVERT_TYPE;
    }

    @Override
    public Field<Integer> field9() {
        return Realty.REALTY_ENTITY.COST;
    }

    @Override
    public Field<Tariff> field10() {
        return Realty.REALTY_ENTITY.TARIFF_TYPE;
    }

    @Override
    public Field<FlatOrHouse> field11() {
        return Realty.REALTY_ENTITY.FLAT_OR_HOUSE;
    }

    @Override
    public Field<LocalDate> field12() {
        return Realty.REALTY_ENTITY.INSERT_DATE;
    }

    @Override
    public Field<LocalDate> field13() {
        return Realty.REALTY_ENTITY.UPDATE_DATE;
    }

    @Override
    public Field<LocalDate> field14() {
        return Realty.REALTY_ENTITY.RELEASE_DATE;
    }

    @Override
    public Field<Realtystatus> field15() {
        return Realty.REALTY_ENTITY.STATUS;
    }

    @Override
    public Field<UUID> field16() {
        return Realty.REALTY_ENTITY.COMPLEX_ID;
    }

    @Override
    public Field<Ownertype> field17() {
        return Realty.REALTY_ENTITY.OWNER_TYPE;
    }

    @Override
    public Field<Boolean> field18() {
        return Realty.REALTY_ENTITY.VERIFY;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getOwnerId();
    }

    @Override
    public Double component3() {
        return getSquare();
    }

    @Override
    public String component4() {
        return getRegion();
    }

    @Override
    public String component5() {
        return getDistrict();
    }

    @Override
    public String component6() {
        return getAddress();
    }

    @Override
    public String component7() {
        return getDescription();
    }

    @Override
    public Adverttype component8() {
        return getAdvertType();
    }

    @Override
    public Integer component9() {
        return getCost();
    }

    @Override
    public Tariff component10() {
        return getTariffType();
    }

    @Override
    public FlatOrHouse component11() {
        return getFlatOrHouse();
    }

    @Override
    public LocalDate component12() {
        return getInsertDate();
    }

    @Override
    public LocalDate component13() {
        return getUpdateDate();
    }

    @Override
    public LocalDate component14() {
        return getReleaseDate();
    }

    @Override
    public Realtystatus component15() {
        return getStatus();
    }

    @Override
    public UUID component16() {
        return getComplexId();
    }

    @Override
    public Ownertype component17() {
        return getOwnerType();
    }

    @Override
    public Boolean component18() {
        return getVerify();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getOwnerId();
    }

    @Override
    public Double value3() {
        return getSquare();
    }

    @Override
    public String value4() {
        return getRegion();
    }

    @Override
    public String value5() {
        return getDistrict();
    }

    @Override
    public String value6() {
        return getAddress();
    }

    @Override
    public String value7() {
        return getDescription();
    }

    @Override
    public Adverttype value8() {
        return getAdvertType();
    }

    @Override
    public Integer value9() {
        return getCost();
    }

    @Override
    public Tariff value10() {
        return getTariffType();
    }

    @Override
    public FlatOrHouse value11() {
        return getFlatOrHouse();
    }

    @Override
    public LocalDate value12() {
        return getInsertDate();
    }

    @Override
    public LocalDate value13() {
        return getUpdateDate();
    }

    @Override
    public LocalDate value14() {
        return getReleaseDate();
    }

    @Override
    public Realtystatus value15() {
        return getStatus();
    }

    @Override
    public UUID value16() {
        return getComplexId();
    }

    @Override
    public Ownertype value17() {
        return getOwnerType();
    }

    @Override
    public Boolean value18() {
        return getVerify();
    }

    @Override
    public RealtyRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public RealtyRecord value2(UUID value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public RealtyRecord value3(Double value) {
        setSquare(value);
        return this;
    }

    @Override
    public RealtyRecord value4(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public RealtyRecord value5(String value) {
        setDistrict(value);
        return this;
    }

    @Override
    public RealtyRecord value6(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public RealtyRecord value7(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public RealtyRecord value8(Adverttype value) {
        setAdvertType(value);
        return this;
    }

    @Override
    public RealtyRecord value9(Integer value) {
        setCost(value);
        return this;
    }

    @Override
    public RealtyRecord value10(Tariff value) {
        setTariffType(value);
        return this;
    }

    @Override
    public RealtyRecord value11(FlatOrHouse value) {
        setFlatOrHouse(value);
        return this;
    }

    @Override
    public RealtyRecord value12(LocalDate value) {
        setInsertDate(value);
        return this;
    }

    @Override
    public RealtyRecord value13(LocalDate value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public RealtyRecord value14(LocalDate value) {
        setReleaseDate(value);
        return this;
    }

    @Override
    public RealtyRecord value15(Realtystatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public RealtyRecord value16(UUID value) {
        setComplexId(value);
        return this;
    }

    @Override
    public RealtyRecord value17(Ownertype value) {
        setOwnerType(value);
        return this;
    }

    @Override
    public RealtyRecord value18(Boolean value) {
        setVerify(value);
        return this;
    }

    @Override
    public RealtyRecord values(UUID value1, UUID value2, Double value3, String value4, String value5, String value6, String value7, Adverttype value8, Integer value9, Tariff value10, FlatOrHouse value11, LocalDate value12, LocalDate value13, LocalDate value14, Realtystatus value15, UUID value16, Ownertype value17, Boolean value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RealtyRecord
     */
    public RealtyRecord() {
        super(Realty.REALTY_ENTITY);
    }

    /**
     * Create a detached, initialised RealtyRecord
     */
    public RealtyRecord(UUID id, UUID ownerId, Double square, String region, String district, String address, String description, Adverttype advertType, Integer cost, Tariff tariffType, FlatOrHouse flatOrHouse, LocalDate insertDate, LocalDate updateDate, LocalDate releaseDate, Realtystatus status, UUID complexId, Ownertype ownerType, Boolean verify) {
        super(Realty.REALTY_ENTITY);

        setId(id);
        setOwnerId(ownerId);
        setSquare(square);
        setRegion(region);
        setDistrict(district);
        setAddress(address);
        setDescription(description);
        setAdvertType(advertType);
        setCost(cost);
        setTariffType(tariffType);
        setFlatOrHouse(flatOrHouse);
        setInsertDate(insertDate);
        setUpdateDate(updateDate);
        setReleaseDate(releaseDate);
        setStatus(status);
        setComplexId(complexId);
        setOwnerType(ownerType);
        setVerify(verify);
    }

    /**
     * Create a detached, initialised RealtyRecord
     */
    public RealtyRecord(RealtyEntity value) {
        super(Realty.REALTY_ENTITY);

        if (value != null) {
            setId(value.getId());
            setOwnerId(value.getOwnerId());
            setSquare(value.getSquare());
            setRegion(value.getRegion());
            setDistrict(value.getDistrict());
            setAddress(value.getAddress());
            setDescription(value.getDescription());
            setAdvertType(value.getAdvertType());
            setCost(value.getCost());
            setTariffType(value.getTariffType());
            setFlatOrHouse(value.getFlatOrHouse());
            setInsertDate(value.getInsertDate());
            setUpdateDate(value.getUpdateDate());
            setReleaseDate(value.getReleaseDate());
            setStatus(value.getStatus());
            setComplexId(value.getComplexId());
            setOwnerType(value.getOwnerType());
            setVerify(value.getVerify());
        }
    }
}
