/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.tables.records;


import com.example.advertismentService.model.jooq.schema.tables.Regions;
import com.example.advertismentService.model.jooq.schema.tables.pojos.RegionsEntity;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegionsRecord extends TableRecordImpl<RegionsRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.regions.code</code>.
     */
    public void setCode(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.regions.code</code>.
     */
    public Integer getCode() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.regions.region_name</code>.
     */
    public void setRegionName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.regions.region_name</code>.
     */
    public String getRegionName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.regions.sales_price</code>.
     */
    public void setSalesPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.regions.sales_price</code>.
     */
    public Integer getSalesPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.regions.rent_price</code>.
     */
    public void setRentPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.regions.rent_price</code>.
     */
    public Integer getRentPrice() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Regions.REGIONS_ENTITY.CODE;
    }

    @Override
    public Field<String> field2() {
        return Regions.REGIONS_ENTITY.REGION_NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Regions.REGIONS_ENTITY.SALES_PRICE;
    }

    @Override
    public Field<Integer> field4() {
        return Regions.REGIONS_ENTITY.RENT_PRICE;
    }

    @Override
    public Integer component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getRegionName();
    }

    @Override
    public Integer component3() {
        return getSalesPrice();
    }

    @Override
    public Integer component4() {
        return getRentPrice();
    }

    @Override
    public Integer value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getRegionName();
    }

    @Override
    public Integer value3() {
        return getSalesPrice();
    }

    @Override
    public Integer value4() {
        return getRentPrice();
    }

    @Override
    public RegionsRecord value1(Integer value) {
        setCode(value);
        return this;
    }

    @Override
    public RegionsRecord value2(String value) {
        setRegionName(value);
        return this;
    }

    @Override
    public RegionsRecord value3(Integer value) {
        setSalesPrice(value);
        return this;
    }

    @Override
    public RegionsRecord value4(Integer value) {
        setRentPrice(value);
        return this;
    }

    @Override
    public RegionsRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegionsRecord
     */
    public RegionsRecord() {
        super(Regions.REGIONS_ENTITY);
    }

    /**
     * Create a detached, initialised RegionsRecord
     */
    public RegionsRecord(Integer code, String regionName, Integer salesPrice, Integer rentPrice) {
        super(Regions.REGIONS_ENTITY);

        setCode(code);
        setRegionName(regionName);
        setSalesPrice(salesPrice);
        setRentPrice(rentPrice);
    }

    /**
     * Create a detached, initialised RegionsRecord
     */
    public RegionsRecord(RegionsEntity value) {
        super(Regions.REGIONS_ENTITY);

        if (value != null) {
            setCode(value.getCode());
            setRegionName(value.getRegionName());
            setSalesPrice(value.getSalesPrice());
            setRentPrice(value.getRentPrice());
        }
    }
}
