/*
 * This file is generated by jOOQ.
 */
package com.example.advertismentService.model.jooq.schema.tables.records;


import com.example.advertismentService.model.jooq.schema.enums.Status;
import com.example.advertismentService.model.jooq.schema.tables.ResidentialComplex;
import com.example.advertismentService.model.jooq.schema.tables.pojos.ResidentialComplexEntity;

import java.time.LocalDate;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResidentialComplexRecord extends UpdatableRecordImpl<ResidentialComplexRecord> implements Record13<UUID, String, String, Integer, Integer, UUID, String, String, String, String, LocalDate, Status, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.residential_complex.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.residential_complex.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.residential_complex.city</code>.
     */
    public void setCity(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.residential_complex.city</code>.
     */
    public String getCity() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.residential_complex.district</code>.
     */
    public void setDistrict(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.residential_complex.district</code>.
     */
    public String getDistrict() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.residential_complex.number_of_buildings</code>.
     */
    public void setNumberOfBuildings(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.residential_complex.number_of_buildings</code>.
     */
    public Integer getNumberOfBuildings() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>public.residential_complex.number_of_ready_buildings</code>.
     */
    public void setNumberOfReadyBuildings(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.residential_complex.number_of_ready_buildings</code>.
     */
    public Integer getNumberOfReadyBuildings() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.residential_complex.builder_id</code>.
     */
    public void setBuilderId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.residential_complex.builder_id</code>.
     */
    public UUID getBuilderId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.residential_complex.name</code>.
     */
    public void setName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.residential_complex.name</code>.
     */
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.residential_complex.description</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.residential_complex.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.residential_complex.link_on_website</code>.
     */
    public void setLinkOnWebsite(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.residential_complex.link_on_website</code>.
     */
    public String getLinkOnWebsite() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.residential_complex.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.residential_complex.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.residential_complex.delivery_year</code>.
     */
    public void setDeliveryYear(LocalDate value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.residential_complex.delivery_year</code>.
     */
    public LocalDate getDeliveryYear() {
        return (LocalDate) get(10);
    }

    /**
     * Setter for <code>public.residential_complex.status</code>.
     */
    public void setStatus(Status value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.residential_complex.status</code>.
     */
    public Status getStatus() {
        return (Status) get(11);
    }

    /**
     * Setter for <code>public.residential_complex.region</code>.
     */
    public void setRegion(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.residential_complex.region</code>.
     */
    public Integer getRegion() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<UUID, String, String, Integer, Integer, UUID, String, String, String, String, LocalDate, Status, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<UUID, String, String, Integer, Integer, UUID, String, String, String, String, LocalDate, Status, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.CITY;
    }

    @Override
    public Field<String> field3() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.DISTRICT;
    }

    @Override
    public Field<Integer> field4() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.NUMBER_OF_BUILDINGS;
    }

    @Override
    public Field<Integer> field5() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.NUMBER_OF_READY_BUILDINGS;
    }

    @Override
    public Field<UUID> field6() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.BUILDER_ID;
    }

    @Override
    public Field<String> field7() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.NAME;
    }

    @Override
    public Field<String> field8() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.DESCRIPTION;
    }

    @Override
    public Field<String> field9() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.LINK_ON_WEBSITE;
    }

    @Override
    public Field<String> field10() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.PHONE_NUMBER;
    }

    @Override
    public Field<LocalDate> field11() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.DELIVERY_YEAR;
    }

    @Override
    public Field<Status> field12() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.STATUS;
    }

    @Override
    public Field<Integer> field13() {
        return ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY.REGION;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCity();
    }

    @Override
    public String component3() {
        return getDistrict();
    }

    @Override
    public Integer component4() {
        return getNumberOfBuildings();
    }

    @Override
    public Integer component5() {
        return getNumberOfReadyBuildings();
    }

    @Override
    public UUID component6() {
        return getBuilderId();
    }

    @Override
    public String component7() {
        return getName();
    }

    @Override
    public String component8() {
        return getDescription();
    }

    @Override
    public String component9() {
        return getLinkOnWebsite();
    }

    @Override
    public String component10() {
        return getPhoneNumber();
    }

    @Override
    public LocalDate component11() {
        return getDeliveryYear();
    }

    @Override
    public Status component12() {
        return getStatus();
    }

    @Override
    public Integer component13() {
        return getRegion();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCity();
    }

    @Override
    public String value3() {
        return getDistrict();
    }

    @Override
    public Integer value4() {
        return getNumberOfBuildings();
    }

    @Override
    public Integer value5() {
        return getNumberOfReadyBuildings();
    }

    @Override
    public UUID value6() {
        return getBuilderId();
    }

    @Override
    public String value7() {
        return getName();
    }

    @Override
    public String value8() {
        return getDescription();
    }

    @Override
    public String value9() {
        return getLinkOnWebsite();
    }

    @Override
    public String value10() {
        return getPhoneNumber();
    }

    @Override
    public LocalDate value11() {
        return getDeliveryYear();
    }

    @Override
    public Status value12() {
        return getStatus();
    }

    @Override
    public Integer value13() {
        return getRegion();
    }

    @Override
    public ResidentialComplexRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value2(String value) {
        setCity(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value3(String value) {
        setDistrict(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value4(Integer value) {
        setNumberOfBuildings(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value5(Integer value) {
        setNumberOfReadyBuildings(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value6(UUID value) {
        setBuilderId(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value7(String value) {
        setName(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value8(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value9(String value) {
        setLinkOnWebsite(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value10(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value11(LocalDate value) {
        setDeliveryYear(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value12(Status value) {
        setStatus(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord value13(Integer value) {
        setRegion(value);
        return this;
    }

    @Override
    public ResidentialComplexRecord values(UUID value1, String value2, String value3, Integer value4, Integer value5, UUID value6, String value7, String value8, String value9, String value10, LocalDate value11, Status value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResidentialComplexRecord
     */
    public ResidentialComplexRecord() {
        super(ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY);
    }

    /**
     * Create a detached, initialised ResidentialComplexRecord
     */
    public ResidentialComplexRecord(UUID id, String city, String district, Integer numberOfBuildings, Integer numberOfReadyBuildings, UUID builderId, String name, String description, String linkOnWebsite, String phoneNumber, LocalDate deliveryYear, Status status, Integer region) {
        super(ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY);

        setId(id);
        setCity(city);
        setDistrict(district);
        setNumberOfBuildings(numberOfBuildings);
        setNumberOfReadyBuildings(numberOfReadyBuildings);
        setBuilderId(builderId);
        setName(name);
        setDescription(description);
        setLinkOnWebsite(linkOnWebsite);
        setPhoneNumber(phoneNumber);
        setDeliveryYear(deliveryYear);
        setStatus(status);
        setRegion(region);
    }

    /**
     * Create a detached, initialised ResidentialComplexRecord
     */
    public ResidentialComplexRecord(ResidentialComplexEntity value) {
        super(ResidentialComplex.RESIDENTIAL_COMPLEX_ENTITY);

        if (value != null) {
            setId(value.getId());
            setCity(value.getCity());
            setDistrict(value.getDistrict());
            setNumberOfBuildings(value.getNumberOfBuildings());
            setNumberOfReadyBuildings(value.getNumberOfReadyBuildings());
            setBuilderId(value.getBuilderId());
            setName(value.getName());
            setDescription(value.getDescription());
            setLinkOnWebsite(value.getLinkOnWebsite());
            setPhoneNumber(value.getPhoneNumber());
            setDeliveryYear(value.getDeliveryYear());
            setStatus(value.getStatus());
            setRegion(value.getRegion());
        }
    }
}
